### ISSUE TITLE
Byte-counter breaks on certain answer

### ISSUE THREAD

**Issue by ETHproductions** [vihanb/PPCG-Design#103]
See http://codegolf.stackexchange.com/a/100934/42545

The userscript doesn't give the code block any byte counter. Is this because the block contains `<DATA>`?

**Comment by JJ-Atkinson** [comment]
Nope, the post is formatted weirdly. Normally the html for the site is `<pre><code>{your code}</code></pre>`, but in this case, the format is just `<pre>{your code}</pre>` because the writer used html tags:

```perl
...bytes

<pre>
undef$/;print&lt;DATA&gt;
__DATA__

</pre>

Trailing newline....
```

I don't know if this should be handled because this is rarely done in posts. 

The code that causes this is here: https://github.com/vihanb/PPCG-Design/blob/master/ppcg.user.js#L616

```JS
function showByteCounts() {
      // ...
      $(this).find("pre code").each(function() {
      // ...
}
```

**Comment by ETHproductions** [comment]
Yeah, I don't think this is important enough to require fixing.
